version: "3.9"

services:
  backend:
    build:
      context: ./chat-backend/
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "13001:13001"
    environment:
      - PORT=13001
      - ENVIRONMENT=development
      - AWS_ACCESS_KEY_ID=your_access_key
      - AWS_SECRET_ACCESS_KEY=your_secret_key
      - AWS_REGION=ap-northeast-1
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - DYNAMO_CHAT_TABLE=Chat
      - DYNAMO_USER_TABLE=ChatUser
      - DYNAMO_MASTER_TABLE=ChatMaster
    depends_on:
      - dynamodb-local
    volumes:
      - ./chat-backend:/app
  frontend:
    build:
      context: ./chat-app/
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3000:3000"
    depends_on:
      - dynamodb-local
    volumes:
      - ./chat-app:/app
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    volumes:
      - dynamodb-chat-data:/data
    ports:
      - 8000:8000
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
volumes:
  dynamodb-chat-data: